version: '3'
services:
  example-db:
    image: "postgres"
    container_name: "rust-users-api"
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"
    volumes:
      - users-api:/var/lib/postgresql/data
volumes:
  users-api: